apiVersion: v1
name: kibana
version: 3.2.4
appVersion: 6.7.0
description: Kibana is an open source data visualization plugin for Elasticsearch
icon: https://helm.elastic.co/icons/kibana.png
keywords:
- elasticsearch
- kibana
maintainers:
- name: compleatang
  email: casey@monax.io
- name: monotek
  email: monotek23@gmail.com
- name: mojab
  email: hello@mojab.org
sources:
- https://github.com/elastic/kibana
engine: gotpl
home: https://www.elastic.co/products/kibana
